Repository mezidia/song-helper, pull requests merged in 2021-07, with the labels that each got.

#92 Update README.md
  README.md
Labels: invalid

#91 Connect song helper
  .env_sample
  .github/workflows/bot.yml
  .github/workflows/django.yml
  .github/workflows/song-helper.yml
  bot/bot.py
  mobileApp/App.js
  server/mesite/admin.py
  server/mesite/migrations/0003_auto_20210717_1926.py
  server/mesite/migrations/0004_auto_20210717_1938.py
  server/mesite/models.py
  server/mesite/searcher.py
  server/mesite/tests.py
  server/mesite/views.py
  server/songhelper/__init__.py
  server/songhelper/config.py
  server/songhelper/create_data_set.py
  server/songhelper/data/MELD-dataset/data/MELD/dev_sent_emo.csv
  server/songhelper/data/MELD-dataset/data/MELD/test_sent_emo.csv
  server/songhelper/data/MELD-dataset/data/MELD/train_sent_emo.csv
  server/songhelper/data/MELD-dataset/data/MELD_Dyadic/dev_sent_emo_dya.csv
  server/songhelper/data/MELD-dataset/data/MELD_Dyadic/test_sent_emo_dya.csv
  server/songhelper/data/MELD-dataset/data/MELD_Dyadic/train_sent_emo_dya.csv
  server/songhelper/data/MELD-dataset/data/emorynlp/emorynlp_dev_final.csv
  server/songhelper/data/MELD-dataset/data/emorynlp/emorynlp_test_final.csv
  server/songhelper/data/MELD-dataset/data/emorynlp/emorynlp_train_final.csv
  server/songhelper/fake_server.py
  server/songhelper/model.py
  server/songhelper/mood_from_words.py
  server/songhelper/mood_predictors.py
  server/songhelper/predict.py
  server/songhelper/requirements.txt
  server/songhelper/test_model.py
  server/songhelper/test_mood_from_words.py
  server/songhelper/test_predict.py
  server/songhelper/test_utils.py
  server/songhelper/test_word_preprocessor.py
  server/songhelper/utils.py
  server/songhelper/words_preprocessor.py
  server/templates/mesite/index.html
  songhelper/.env_sample
Labels: django, mobile app, telegram bot

#95 Update README.md
  README.md
Labels: enhancement
